---
title: "Desafio 4"
author: "Luiz Eduardo Rodrigues"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(leaflet)
library(lubridate)
```

Função do Desafio

```{r}
analisa_aeronave <- function(tail_number, arquivo) {
  airports <- read_csv("Dados/airports.csv") %>%
    select(origin = IATA_CODE, lat = LATITUDE, lon = LONGITUDE)
  flights_data <- read_csv(arquivo) %>%
    filter(TAIL_NUMBER == tail_number) %>%
    mutate(DEPARTURE_TIME = as.numeric(DEPARTURE_TIME)) %>%
    drop_na(ORIGIN_AIRPORT, DESTINATION_AIRPORT, DEPARTURE_TIME) %>%
    arrange(YEAR, MONTH, DAY, DEPARTURE_TIME) %>%
    mutate(flight_time = AIR_TIME / 60,
      avg_speed = DISTANCE / flight_time) %>%
    left_join(airports, by = c("ORIGIN_AIRPORT" = "origin")) %>%
    rename(orig_lat = lat, orig_lon = lon) %>%
    left_join(airports, by = c("DESTINATION_AIRPORT" = "origin")) %>%
    rename(dest_lat = lat, dest_lon = lon) %>%
    mutate(dep_datetime = make_datetime(YEAR, MONTH, DAY,
        floor(DEPARTURE_TIME / 100), DEPARTURE_TIME %% 100))
  
  map <- leaflet() %>% addTiles() %>% addCircleMarkers(data = airports,
      lng = ~lon, lat = ~lat, radius = 3, popup = ~origin)
 
  for(i in 1:nrow(flights_data)) {
    map <- map %>% addPolylines(
        lng = c(flights_data$orig_lon[i], flights_data$dest_lon[i]),
        lat = c(flights_data$orig_lat[i], flights_data$dest_lat[i]),
        weight = flights_data$avg_speed[i] / 100,  
        popup = paste("Voo:", flights_data$ORIGIN_AIRPORT[i],
                     "para", flights_data$DESTINATION_AIRPORT[i],
                     "<br>Velocidade média:", round(flights_data$avg_speed[i], 1),                      "mph", "<br>Data:", flights_data$dep_datetime[i]))}
 
  return(list(tabela = flights_data, mapa = map))}

resultado <- analisa_aeronave("N431WN", "Dados/flights.csv")
 resultado$tabela
 resultado$mapa
```
